### ISSUE TITLE
The displayed Name and Hex properties are empty

### ISSUE THREAD

**Issue by sba923** [StartAutomating/Emoji#59]
I've tried the example given in https://twitter.com/JamesBru/status/1761091548383707161.

All I get (both in Windows PowerShell 5.1.19041.4046 and in PowerShell 7.4.1) is:

![image](https://github.com/StartAutomating/Emoji/assets/12860484/67e0d51a-ff3f-47c6-a523-3927e1470882)

(OS is Windows 10 build 10.0.19041.4046)

**Comment by StartAutomating** [comment]
Thank you for the reminder....

To mark this module as only working on core.

Most of the Emoji will not render on non-core, and the escape sequence is not supported.

**Comment by sba923** [comment]
It also fails with 7.4.1!

Here's what `$error` has to say:

![image](https://github.com/StartAutomating/Emoji/assets/12860484/55a7ad25-0d63-425a-a5ca-f9bf3490fd4f)

**Comment by StartAutomating** [comment]
@sba923 Still looks very weird.  I don't _think_ oh-my-posh is doing it, but trying without that might work.

The other guess I have is execution policy (it could be affecting the types files more silently than I would like).

**Comment by sba923** [comment]
Launching `oh-my-posh` with the same arguments as from my profile doesn't break `Get-Emoji`:

![image](https://github.com/StartAutomating/Emoji/assets/12860484/ef7e2e4b-ff10-4b82-9308-b649a26c3107)

**Comment by StartAutomating** [comment]
The place that is complaining is related to colorization / style, and _might_ be tripped if $psStyle was set to an unexpected value.

If this is the case, you should also see colorization errors if you load up [Posh](https://github.com/StartAutomating/Posh)

If you do, then the actual issue is in [EZOut](https://github.com/StartAutomating/EZOut) (which builds formatters for all of these things)

**Comment by sba923** [comment]
Does this shed some light on the issue?

![image](https://github.com/StartAutomating/Emoji/assets/12860484/c1390227-21b2-40ba-b5d6-3c7631a4c50a)

**Comment by StartAutomating** [comment]
Yeah and no.  Based off of what you've already sent I already know it's related to $psStyle and how colorization is handled.

But not _why_ it's broken, or _how_.

Can you poke at $psStyle a bit when it's not broken and see what might be going on?

**Comment by sba923** [comment]
`$PSStyle` is identical in broken and non-broken sessions.

`Posh` _doesn't break_ `Get-Emoji`'s output.

**Comment by sba923** [comment]
And the culprit is...🥁

`Set-StrictMode -Version latest`

**Comment by StartAutomating** [comment]
Glad we've found the culprit!

You should be able to reproduce this in EZOut by creating any formatter that uses -Style* parameters:

https://twitter.com/SBarizien/status/1766043978640585185 (just add -StyleProperty to your example)

**Comment by sba923** [comment]
Fix confirmed, good job!

![image](https://github.com/StartAutomating/Emoji/assets/12860484/5944c08b-06c7-4f1b-bae7-a3faa1777ac9)
